/**
 * 球队英文 -> 中文名映射。
 * football-data.org 不提供中文名，自己维护一张表。
 *
 * 匹配策略：按 SUBSTR 列表顺序做 includes 匹配（最先匹中即返回）。
 * 因此**必须把更具体/更长的子串放在前面**，否则会被短串吃掉，
 * 例如 "Manchester United" 必须排在 "Manchester City" 之前是错的（两者互不包含），
 * 但 "Real Sociedad" 必须排在 "Real" 之前。
 *
 * 找不到时返回 null，调用方回落到英文 name。
 */

const SUBSTR: Array<[string, string]> = [
  // ---------- 英超 (PL) ----------
  ["Manchester United", "曼联"],
  ["Manchester City", "曼城"],
  ["Tottenham", "热刺"],
  ["Liverpool", "利物浦"],
  ["Chelsea", "切尔西"],
  ["Arsenal", "阿森纳"],
  ["Newcastle", "纽卡斯尔联"],
  ["Aston Villa", "维拉"],
  ["Brighton", "布莱顿"],
  ["West Ham", "西汉姆联"],
  ["Crystal Palace", "水晶宫"],
  ["Brentford", "布伦特福德"],
  ["Fulham", "富勒姆"],
  ["Wolverhampton", "狼队"],
  ["Everton", "埃弗顿"],
  ["Leeds", "利兹联"],
  ["Bournemouth", "伯恩茅斯"],
  ["Nottingham", "诺丁汉森林"],
  ["Burnley", "伯恩利"],
  ["Sunderland", "桑德兰"],
  ["Sheffield United", "谢菲尔德联"],
  ["Sheffield Wednesday", "谢菲尔德星期三"],
  ["Luton", "卢顿"],
  ["Ipswich", "伊普斯维奇"],
  ["Leicester", "莱斯特城"],

  // ---------- 西甲 (PD) ----------
  ["Real Madrid", "皇家马德里"],
  ["Barcelona", "巴塞罗那"],
  ["Atlético", "马德里竞技"],
  ["Atletico Madrid", "马德里竞技"],
  ["Athletic", "毕尔巴鄂竞技"],
  ["Real Sociedad", "皇家社会"],
  ["Real Betis", "皇家贝蒂斯"],
  ["Sevilla", "塞维利亚"],
  ["Valencia", "巴伦西亚"],
  ["Villarreal", "比利亚雷亚尔"],
  ["Getafe", "赫塔菲"],
  ["Girona", "赫罗纳"],
  ["Celta", "塞尔塔"],
  ["Rayo Vallecano", "巴列卡诺"],
  ["Espanyol", "西班牙人"],
  ["Mallorca", "马洛卡"],
  ["Osasuna", "奥萨苏纳"],
  ["Alavés", "阿拉维斯"],
  ["Alaves", "阿拉维斯"],
  ["Levante", "莱万特"],
  ["Oviedo", "奥维耶多"],
  ["Elche", "埃尔切"],
  ["Cádiz", "加的斯"],
  ["Granada", "格拉纳达"],
  ["Las Palmas", "拉斯帕尔马斯"],

  // ---------- 意甲 (SA) ----------
  ["Internazionale", "国际米兰"],
  ["Inter Milan", "国际米兰"],
  ["AC Milan", "AC米兰"],
  ["Juventus", "尤文图斯"],
  ["Napoli", "那不勒斯"],
  ["Roma", "罗马"],
  ["Lazio", "拉齐奥"],
  ["Atalanta", "亚特兰大"],
  ["Fiorentina", "佛罗伦萨"],
  ["Bologna", "博洛尼亚"],
  ["Torino", "都灵"],
  ["Udinese", "乌迪内斯"],
  ["Genoa", "热那亚"],
  ["Sassuolo", "萨索洛"],
  ["Cagliari", "卡利亚里"],
  ["Verona", "维罗纳"],
  ["Empoli", "恩波利"],
  ["Parma", "帕尔马"],
  ["Como", "科莫"],
  ["Lecce", "莱切"],
  ["Pisa", "比萨"],
  ["Monza", "蒙扎"],
  ["Salernitana", "萨勒尼塔纳"],
  ["Frosinone", "弗罗西诺内"],
  ["Cremonese", "克雷莫纳"],
  ["Venezia", "威尼斯"],

  // ---------- 德甲 (BL1) ----------
  ["Bayern", "拜仁慕尼黑"],
  ["Borussia Dortmund", "多特蒙德"],
  ["Borussia Mönchengladbach", "门兴格拉德巴赫"],
  ["RB Leipzig", "莱比锡"],
  ["Leverkusen", "勒沃库森"],
  ["Eintracht Frankfurt", "法兰克福"],
  ["Stuttgart", "斯图加特"],
  ["Wolfsburg", "沃尔夫斯堡"],
  ["Freiburg", "弗赖堡"],
  ["Hoffenheim", "霍芬海姆"],
  ["Heidenheim", "海登海姆"],
  ["Augsburg", "奥格斯堡"],
  ["Köln", "科隆"],
  ["Koln", "科隆"],
  ["Werder Bremen", "云达不来梅"],
  ["Mainz", "美因茨"],
  ["St. Pauli", "圣保利"],
  ["St Pauli", "圣保利"],
  ["Union Berlin", "柏林联合"],
  ["Hamburger SV", "汉堡"],
  ["Hertha", "柏林赫塔"],
  ["Schalke", "沙尔克04"],

  // ---------- 法甲 (FL1) ----------
  ["Paris Saint-Germain", "巴黎圣日耳曼"],
  ["Paris Saint Germain", "巴黎圣日耳曼"],
  ["Marseille", "马赛"],
  ["Monaco", "摩纳哥"],
  ["Lille", "里尔"],
  ["Olympique Lyonnais", "里昂"],
  ["Lyon", "里昂"],
  ["Rennais", "雷恩"],
  ["Rennes", "雷恩"],
  ["Nice", "尼斯"],
  ["Lens", "朗斯"],
  ["Strasbourg", "斯特拉斯堡"],
  ["Toulouse", "图卢兹"],
  ["Brestois", "布雷斯特"],
  ["Le Havre", "勒阿弗尔"],
  ["Angers", "昂热"],
  ["Auxerre", "欧塞尔"],
  ["Saint-Étienne", "圣埃蒂安"],
  ["Saint-Etienne", "圣埃蒂安"],
  ["Nantes", "南特"],
  ["Paris FC", "巴黎FC"],
  ["Metz", "梅斯"],
  ["Lorient", "洛里昂"],
  ["Reims", "兰斯"],
  ["Montpellier", "蒙彼利埃"],
  ["Clermont", "克莱蒙"],

  // ---------- 欧冠 / 欧联 常见 ----------
  ["Benfica", "本菲卡"],
  ["Sporting", "葡萄牙体育"],
  ["Porto", "波尔图"],
  ["Braga", "布拉加"],
  ["PSV", "埃因霍温"],
  ["Eindhoven", "埃因霍温"],
  ["Ajax", "阿贾克斯"],
  ["Feyenoord", "费耶诺德"],
  ["Celtic", "凯尔特人"],
  ["Rangers", "流浪者"],
  ["Galatasaray", "加拉塔萨雷"],
  ["Beşiktaş", "贝西克塔什"],
  ["Besiktas", "贝西克塔什"],
  ["Fenerbahçe", "费内巴切"],
  ["Fenerbahce", "费内巴切"],
  ["Trabzonspor", "特拉布宗"],
  ["Kobenhavn", "哥本哈根"],
  ["København", "哥本哈根"],
  ["Copenhagen", "哥本哈根"],
  ["Salzburg", "萨尔茨堡"],
  ["Rapid Wien", "维也纳快速"],
  ["Sturm Graz", "格拉茨风暴"],
  ["Slavia Praha", "布拉格斯拉维亚"],
  ["Sparta Praha", "布拉格斯巴达"],
  ["Olympiacos", "奥林匹亚科斯"],
  ["Panathinaikos", "帕纳辛奈科斯"],
  ["AEK Athens", "雅典AEK"],
  ["Crvena Zvezda", "红星贝尔格莱德"],
  ["Partizan", "贝尔格莱德游击"],
  ["Shakhtar", "顿涅茨克矿工"],
  ["Dynamo Kyiv", "基辅迪纳摩"],
  ["Dinamo Zagreb", "萨格勒布迪纳摩"],
  ["Hajduk", "哈伊杜克"],
  ["Young Boys", "年轻人"],
  ["Basel", "巴塞尔"],
  ["Bodø/Glimt", "博德闪耀"],
  ["Bodo Glimt", "博德闪耀"],
  ["Bodø", "博德闪耀"],
  ["Pafos", "帕福斯"],
  ["Club Brugge", "布鲁日"],
  ["Anderlecht", "安德莱赫特"],
  ["Saint-Gilloise", "圣吉罗斯联"],
  ["Qarabağ", "卡拉巴克"],
  ["Qarabag", "卡拉巴克"],
  ["Kairat", "阿拉木图卡拉特"],
  ["Maccabi", "特拉维夫马卡比"],
  ["Hapoel", "特拉维夫夏普尔"],
  ["AZ", "阿尔克马尔"],
  ["FC Twente", "特温特"],
  ["Utrecht", "乌德勒支"],
  ["Toulouse", "图卢兹"],

  // ---------- 国家队 (WC) ----------
  ["Argentina", "阿根廷"],
  ["Brazil", "巴西"],
  ["France", "法国"],
  ["England", "英格兰"],
  ["Spain", "西班牙"],
  ["Germany", "德国"],
  ["Portugal", "葡萄牙"],
  ["Netherlands", "荷兰"],
  ["Italy", "意大利"],
  ["Belgium", "比利时"],
  ["Croatia", "克罗地亚"],
  ["Uruguay", "乌拉圭"],
  ["Colombia", "哥伦比亚"],
  ["Mexico", "墨西哥"],
  ["United States", "美国"],
  ["USA", "美国"],
  ["Canada", "加拿大"],
  ["Japan", "日本"],
  ["South Korea", "韩国"],
  ["Korea Republic", "韩国"],
  ["Iran", "伊朗"],
  ["Saudi Arabia", "沙特阿拉伯"],
  ["Qatar", "卡塔尔"],
  ["Australia", "澳大利亚"],
  ["Morocco", "摩洛哥"],
  ["Senegal", "塞内加尔"],
  ["Tunisia", "突尼斯"],
  ["Ghana", "加纳"],
  ["Nigeria", "尼日利亚"],
  ["Cameroon", "喀麦隆"],
  ["Ivory Coast", "科特迪瓦"],
  ["Côte d'Ivoire", "科特迪瓦"],
  ["Egypt", "埃及"],
  ["Algeria", "阿尔及利亚"],
  ["Switzerland", "瑞士"],
  ["Denmark", "丹麦"],
  ["Sweden", "瑞典"],
  ["Norway", "挪威"],
  ["Poland", "波兰"],
  ["Serbia", "塞尔维亚"],
  ["Wales", "威尔士"],
  ["Scotland", "苏格兰"],
  ["Ireland", "爱尔兰"],
  ["Austria", "奥地利"],
  ["Czech", "捷克"],
  ["Türkiye", "土耳其"],
  ["Turkey", "土耳其"],
  ["Ukraine", "乌克兰"],
  ["Ecuador", "厄瓜多尔"],
  ["Chile", "智利"],
  ["Peru", "秘鲁"],
  ["Paraguay", "巴拉圭"],
  ["Venezuela", "委内瑞拉"],
  ["Bolivia", "玻利维亚"],
  ["Costa Rica", "哥斯达黎加"],
  ["Panama", "巴拿马"],
  ["Honduras", "洪都拉斯"],
  ["Jamaica", "牙买加"],
  ["New Zealand", "新西兰"],
  ["China PR", "中国"],
  ["China", "中国"],
];

export function teamNameZh(en: string): string | null {
  for (const [needle, zh] of SUBSTR) {
    if (en.includes(needle)) return zh;
  }
  return null;
}

export function displayTeamName(en: string): string {
  return teamNameZh(en) ?? en;
}
